language: node_js
node_js:
- stable
before_deploy:
- |
  if ! [ "$BEFORE_DEPLOY_RUN" ]; then
    export BEFORE_DEPLOY_RUN=1;
    npm run-script build-demo
  fi
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: Y5Va+kUT0ObgYcsY5VOgfZTdNuBzmAhZYduVbPdmqz5ne4KtGXVsUYMTM64zFFjSgRL9/dCHKdptmQ2Jk0nk8r7XTSWEUQRSrIMgeXxa8DDZnGYQGtgAJnBN2zBO3g03frvClqzV/KHBIub+yNhZHVtShl8cIrhNerTDI3B/isN2Qlh0gqQAeq018s/ujihdzfhMVZWNxDHjfJ3xbuJIhrNCinJ3K8C9GdzgizmHAZmiTNXqgp2QOciC5IqWfzIk7wUZk+P6kOH46bUFjDnxpb47/IqPNOz8Rrsuk+jZMuRg0Oh1uqLrD95+7CRB97O2u9XOfNt9J3jKjL3FIRYAwTMXglVW0NB6Z6Pqc9h27euqcypMfvfObH/yy57Lq3qdI0FpOaG8ZvtSybnirXJ+g+Axh9U5dzbvc+88FRELitb35D6AIE0AZymV/0tJUrghZGqtf2RD06Xpi6M+cKVEsFrvO+0V8rhkRu02EHplGTxWGuuwGs1QpG36CR+obNj9RDXKMl1SbVlMomn35h/1HkvIeaZwMfB7KqaLyXzS0EpSfbdbgVseCWMXw/OXmdNCgY0BwLzRx1RxD50kUdv690EOHugy+QIsvEuJqPQ2enrG1cAkgk0TKDd3QlQe5kTKH/aVQQ36SSYfvJ30ngFtNy1k415ZWjixbmYpTRME7uQ=
  on:
    tags: true
    repo: DEGJS/fetchUtils
